# Save!
# quarto render -- updates the site
# quarto preview (maybe; if you want to check before updating actual site)
# Then add, commit, push

project:
  type: website

website:
  title: Nicholas Cassol-Pawson
  page-footer: "© 2025, Nicholas Cassol-Pawson"
  navbar:
    left:
      - href: index.qmd
        text: Home # Removing this changes the title to the project title
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: 
      light: [lightly, theme-light.scss] # Template colors, text styles: darkly, lumen, morph
      dark: [darkly, theme-dark.scss]

    css: styles.css # This needs CSS work to change
    #toc: true

editor: visual

execute: 
  freeze: auto # Caches the document — only rerenders old documents